# Generated by Django 2.1.7 on 2024-08-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=500)),
                ('phone', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=300)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(max_length=800)),
                ('maxspeed', models.IntegerField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
