# Generated by Django 5.1 on 2024-08-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ccequivalent',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='range',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('red', 'Red'), ('grey', 'Grey'), ('green', 'Green'), ('blue', 'Blue'), ('white', 'White')], default='red', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='maxspeed',
            field=models.CharField(max_length=200),
        ),
    ]
