# Generated by Django 5.1 on 2024-08-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_battery_product_ccequivalent_product_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chargetime',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='netwt',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='peaktorque',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='ratedpeakpower',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
